[package]
name = "shaded_sun"
version = "0.0.0"
authors = ["CatCode <andrea.postal@gmail.com>"]
edition = "2018"
description = "Shaded Sun Videogame"
publish = false

[dependencies.irid]
path = "../irid"
version = "0.0"

[dependencies]
env_logger = "0.9"
log = "0.4"
wgpu = "0.10"
winit = "0.25"
