[package]
name = "bad"
version = "0.1.3"
authors = ["CatCode <andrea.postal@gmail.com>"]
edition = "2018"
description = "Black Abyss Dungeon"
publish = false

[dependencies]
cgmath = "0.18"
env_logger = "0.8"
futures = "0.3"
image = "0.23"
log = "0.4"
wgpu = "0.8"
winit = "0.24"

[build-dependencies]
anyhow = "1.0"
fs_extra = "1.2"
glob = "0.3"
shaderc = "0.7"
