[workspace]

members = [
    "bad",
    "irid",
    "learnwgpu/learnwgpu_01_window",
    "learnwgpu/learnwgpu_02_swapchain",
    "learnwgpu/learnwgpu_03_pipeline",
    "learnwgpu/learnwgpu_04_buffers_indices",
    "learnwgpu/learnwgpu_07_instancing",
]
