[package]
name = "irid_traits"
version = "0.0.14"
authors = ["CatCode79"]
edition = "2021"
rust-version = "1.66"
description = "Irid Game Framework Renderer"
repository = "https://github.com/CatCode79/irid"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
