[package]
name = "learnwgpu_07_instancing"
version = "0.0.1"
authors = ["CatCode <andrea.postal@gmail.com>"]
edition = "2021"
description = "based on https://sotrh.github.io/learn-wgpu/beginner/tutorial7-instancing/"

[dependencies]
env_logger = "0.9"
log = "0.4"
wgpu = "0.10"
winit = "0.25"

[dependencies.irid]
path = "../../irid"
version = "0.0"
