[package]
name = "irid_renderer"
version = "0.0.12"
authors = ["https://github.com/irid-game-framework/irid/graphs/contributors"]
edition = "2018"
#rust-version = "1.48"
description = "Irid Game Framework Renderer"
repository = "https://github.com/irid-game-framework/irid"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
bytemuck = { version = "1.7", features = ["derive"] }
cgmath = "0.18"
image = "0.23"
irid_app_interface = { path = "../irid_app_interface" }
irid_assets = { path = "../irid_assets" }
irid_assets_interface = { path = "../irid_assets_interface" }
irid_renderer_interface = { path = "../irid_renderer_interface" }
log = "0.4"
pollster = "0.2"
thiserror = "1.0"
wgpu = "0.12"
winit = "0.26"
