[package]
name = "irid"
version = "0.0.33"
authors = ["CatCode <andrea.postal@gmail.com>"]
edition = "2018"

[dependencies]
#anyhow = "1.0"  # It have the no_std feature
bytemuck = { version = "1.7", features = ["derive"] }
cgmath = "0.18"
futures = "0.3"
image = "0.23"
log = "0.4"
wgpu = "0.10"
winit = "0.25"

[features]
default = ["debug_label"]
debug_label = []
