[package]
name = "learnwgpu_02_swapchain"
version = "0.0.1"
authors = ["CatCode <andrea.postal@gmail.com>"]
edition = "2021"
description = "based on https://sotrh.github.io/learn-wgpu/beginner/tutorial2-surface/"

[dependencies]
env_logger = "0.8"
wgpu = "0.10"
winit = "0.25"

[dependencies.irid]
path = "../../irid"
version = "0.0"
